export const DataDisenoWeb = [
  {
    name: "ONE Page",
    descriptionCorta: "Destaca con una identidad visual única.",
    details: [
      {
        name: "Incluye",
        items: [
          "1 sección",
          "Optimización SEO",
          "Autoadministrable (Wordpress)",
          "Diseño responsive",
          "Hasta 20 productos",
          "Capacitación de 1 hora",
          "Desarrollo en plantilla (Elementor Pro)",
          "Hosting 5GB",
          "Proveedor Hostinger",
          "Ram 6 GB",
          "CPU 4 Núcleos",
          "Incluye certificado SSL",
          "Ancho de banda ilimitado",
          "Incluye elementor Pro",
          "Incluye 3 correos corporativos",
          "Copias de seguridad diarias",
          "Incluye protección de dominio (WHOIS)",
          "Incluye antivirus",
          "Soporte 24/7",
          "Precio anual Hosting: S/ 100.00",
          "Precio anual Dominio: S/ 50.00",
          "Precio anual Dominio.pe: S/ 110.00",
        ],
      },
      {
        name: "Precios incluye IGV"
      }
    ],
    price: 600.00,
    color: "#0BC2E1",
    word: "Costo de desarrollo",
  },
  {
    name: "WEB EMPRESARIAL",
    descriptionCorta: "Destaca con una identidad visual única.",
    details: [
      {
        name: "Incluye",
        items: [
          "5 secciones",
          "Optimización SEO",
          "Autoadministrable (Wordpress)",
          "Diseño responsive",
          "Hasta 100 productos",
          "Capacitación de 1 hora",
          "Desarrollo en plantilla (Elementor Pro)",
          "Hosting 10 GB",
          "Proveedor Hostinger",
          "Ram 6 GB",
          "CPU 4 Núcleos",
          "Incluye certificado SSL",
          "Ancho de banda ilimitado",
          "Incluye elementor Pro",
          "Incluye 5 correos corporativos",
          "Copias de seguridad diarias",
          "Incluye protección de dominio (WHOIS)",
          "Incluye antivirus",
          "Soporte 24/7",
          "Precio anual Hosting: S/ 150.00",
          "Precio anual Dominio: S/ 50.00",
          "Precio anual Dominio.pe: S/ 110.00",
        ],
      },
      {
        name: "Precios incluye IGV"
      }
    ],
    price: 1200.00,
    color: "#0BC2E1",
    word: "Costo de desarrollo",
  },
  {
    name: "WEB CORPORATIVA",
    descriptionCorta: "Destaca con una identidad visual única.",
    details: [
      {
        name: "Incluye",
        items: [
          "8 secciones",
          "Optimización SEO",
          "Autoadministrable (Wordpress)",
          "Diseño responsive",
          "Hasta 1000 productos",
          "Capacitación de 2 hora",
          "Desarrollo en plantilla (Elementor Pro)",
          "Hosting 10 GB",
          "Proveedor Hostinger",
          "Ram 6 GB",
          "CPU 4 Núcleos",
          "Incluye certificado SSL",
          "Ancho de banda ilimitado",
          "Incluye elementor Pro",
          "Incluye 8 correos corporativos",
          "Copias de seguridad diarias",
          "Incluye protección de dominio (WHOIS)",
          "Incluye antivirus",
          "Soporte 24/7",
          "Precio anual Hosting: S/ 150.00",
          "Precio anual Dominio: S/ 50.00",
          "Precio anual Dominio.pe: S/ 110.00",
        ],
      },
    ],
    price: 1500.00,
    color: "#0BC2E1",
    word: "Costo de desarrollo",
  },
  {
    name: "WEB E-COMMERCE",
    descriptionCorta: "Destaca con una identidad visual única.",
    details: [
      {
        name: "Incluye",
        items: [
          "8 secciones",
          "Optimización SEO",
          "Autoadministrable (Wordpress)",
          "Diseño responsive",
          "Hasta 2000 productos",
          "Incluye pasarela de pagos",
          "Capacitación de 2 hora",
          "Desarrollo en plantilla (Elementor Pro)",
          "Hosting 20 GB",
          "Proveedor Hostinger",
          "Ram 6 GB",
          "CPU 4 Núcleos",
          "Incluye certificado SSL",
          "Ancho de banda ilimitado",
          "Incluye elementor Pro",
          "Incluye 10 correos corporativos",
          "Copias de seguridad diarias",
          "Incluye protección de dominio (WHOIS)",
          "Incluye antivirus",
          "Soporte 24/7",
          "Precio anual Hosting: S/ 200.00",
          "Precio anual Dominio: S/ 50.00",
          "Precio anual Dominio.pe: S/ 110.00",
        ],
      },
    ],
    price: 2000.00,
    color: "#0BC2E1",
    word: "Costo de desarrollo",
  },
  {
    name: "WEB A MEDIDA",
    descriptionCorta: "Destaca con una identidad visual única.",
    details: [
      {
        name: "Incluye",
        items: [
          "8 secciones",
          "Optimización SEO",
          "Autoadministrable (Wordpress)",
          "Diseño responsive",
          "Productos ilimitados",
          "Incluye pasarela de pagos",
          "Capacitación de 4 hora",
          "Desarrollo en código fuente NodeJs, PHP",
          "Hosting 50 GB",
          "Proveedor Hostinger",
          "Ram 6 GB",
          "CPU 4 Núcleos",
          "Incluye certificado SSL",
          "Ancho de banda ilimitado",
          "Incluye elementor Pro",
          "Incluye 20 correos corporativos",
          "Copias de seguridad diarias",
          "Incluye protección de dominio (WHOIS)",
          "Incluye antivirus",
          "Soporte 24/7",
          "Precio anual Hosting: S/ 300.00",
          "Precio anual Dominio: S/ 50.00",
          "Precio anual Dominio.pe: S/ 110.00",
        ],
      },
      {
        name: "Precios incluye IGV"
      }
    ],
    price: 5000,
    color: "#0BC2E1",
    word: "Costo de desarrollo",
  },
];
